import {AiFillStar} from "react-icons/ai"

const data = [
    {
        id: 1,
        img: "https://m.media-amazon.com/images/I/61q3fuPKyDL._AC_SX569_.jpg",
        title: "Black Polo",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$150.00",
        newPrice: "100",
        company: "TACVASEN",
        color: "black",
        category: "t-shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 2,
        img: "https://m.media-amazon.com/images/I/5153qtNjk2L._AC_SX569_.jpg",
        title: "Black Hoodie",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(1500 reviews)",
        prevPrice: "$100.00",
        newPrice: "50",
        company: "Lauweion",
        color: "black",
        category: "hoodies",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 3,
        img: "https://m.media-amazon.com/images/I/81bhsYSa6mL._AC_SX569_.jpg",
        title: "Blue Polo",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(10 reviews)",
        prevPrice: "$50.00",
        newPrice: "150",
        company: "Gildan",
        color: "blue",
        category: "t-shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 4,
        img: "https://m.media-amazon.com/images/I/71TiPahKowL._AC_SX569_.jpg",
        title: "Green Round",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(10000 reviews)",
        prevPrice: "$100.00",
        newPrice: "200",
        company: "ZEROYAA",
        color: "green",
        category: "t-shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 5,
        img: "https://m.media-amazon.com/images/I/61un-q29ERL._AC_SX679_.jpg",
        title: "Pink Round",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$40.00",
        newPrice: "150",
        company: "JC DISTRO",
        color: "pink",
        category: "t-shirts",
        gender: "female",
        availableQuantity: 5
    },
    {
        id: 6,
        img: "https://m.media-amazon.com/images/I/61MW+NVBwfL._AC_SL1292_.jpg",
        title: "Pink-Hoodie",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$130.00",
        newPrice: "150",
        company: "BETTERCHIC",
        color: "pink",
        category: "hoodies",
        gender: "female",
        availableQuantity: 5
    },
    {
        id: 7,
        img: "https://m.media-amazon.com/images/I/718b5hgwjiL._AC_SX679_.jpg",
        title: "White round",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$99.00",
        newPrice: "150",
        company: "ARMOUR",
        color: "white",
        category: "t-shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 8,
        img: "https://m.media-amazon.com/images/I/71AqWMkQrRL._AC_SX569_.jpg",
        title: "Black Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$59.00",
        newPrice: "100",
        company: "CHILDREN's PLACE",
        color: "black",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 9,
        img: "https://m.media-amazon.com/images/I/61Qxi8EAa6L._AC_SX679_.jpg",
        title: "Pink Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$69.00",
        newPrice: "100",
        company: "CHILDREN's PLACE",
        color: "pink",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 10,
        img: "https://m.media-amazon.com/images/I/51pnfKCm0TL._AC_SX569_.jpg",
        title: "White Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$149.00",
        newPrice: "200",
        company: "SPRING&GEGE",
        color: "white",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 11,
        img: "https://m.media-amazon.com/images/I/61Qx09RgdVL._AC_SX569_.jpg",
        title: "Light Green Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$139.00",
        newPrice: "200",
        company: "SPRING&GEGE",
        color: "green",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    },

    {
        id: 12,
        img: "https://m.media-amazon.com/images/I/61IeIe-2meL._AC_SX679_.jpg",
        title: "Red Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$100.00",
        newPrice: "150",
        company: "SPRING&GEGE",
        color: "red",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    },{
        id: 13,
        img: "https://m.media-amazon.com/images/I/71L6WW9VG0L._AC_SX679_.jpg",
        title: "Blue Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$50.00",
        newPrice: "100",
        company: "SPRING&GEGE",
        color: "blue",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    },
    {
        id: 14,
        img: "https://m.media-amazon.com/images/I/61Et6kbJidL._AC_SX679_.jpg",
        title: "Dark Green Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$15.00",
        newPrice: "50",
        company: "SPRING&GEGE",
        color: "green",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    },

    {
        id: 15,
        img: "https://m.media-amazon.com/images/I/61-Nua-1rJL._AC_SX679_.jpg",
        title: "Voilet Shirt",
        star: <AiFillStar className="ratings-start"/>,
        reviews:"(123 reviews)",
        prevPrice: "$20.00",
        newPrice: "50",
        company: "SPRING&GEGE",
        color: "voilet",
        category: "shirts",
        gender: "male",
        availableQuantity: 5
    }    
]

export default data;